gitops-runtime:
  global:
    codefresh:
      accountId: 68f0542e82b3b269dffa8189
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
