apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-wizeline
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: poc-project-wizeline
spec:
  project: default
  destination:
    name: in-cluster
    namespace: codefresh-demo
  source:
    path: .
    repoURL: https://github.com/moballiachi/codefresh-gitops-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
